/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import entidades.Jogo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.JogoDAO;


/**
 *
 * @author rodri
 */
public class TelaListaJogoAlugar extends javax.swing.JFrame {
    private List<Jogo>listaJogos;
    /**
     * Creates new form TelaListaJogo
     */
    public TelaListaJogoAlugar() {
        initComponents();
        listarJogos();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabJogos = new javax.swing.JTable();
        btnAdicionaJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Categoria", "Preço", "Nº Dias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabJogos);

        btnAdicionaJogo.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btnAdicionaJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.jpg"))); // NOI18N
        btnAdicionaJogo.setText("Adicionar Jogo");
        btnAdicionaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btnAdicionaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAdicionaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionaJogoActionPerformed
    public void listarJogos(){
        listaJogos=JogoDAO.listar();
        DefaultTableModel modelo=(DefaultTableModel) tabJogos.getModel();
        modelo.setRowCount(0);//Limpar os itens da tabela;
        for(Jogo j:listaJogos){
            Object[] linha={
                j.getTitulo(),
                j.getCategoria().getNome(),
                j.getPreco(),
                j.getNumeroDias()
            };
            modelo.addRow(linha);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaJogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabJogos;
    // End of variables declaration//GEN-END:variables
}
